language: generic
dist: trusty

git:
  depth: 1

script:
  - emacs --version

jobs:
  include:
    - if: branch = master
      stage: "Create recipe"
      script:
        - make clean-recipe
        - make recipe
        - make commit
